//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Subject {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Subject() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Subject", typeof(Subject).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 古纸 的本地化字符串。
        /// </summary>
        public static string Subject01Title01 {
            get {
                return ResourceManager.GetString("Subject01Title01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蔡侯纸 的本地化字符串。
        /// </summary>
        public static string Subject01Title02 {
            get {
                return ResourceManager.GetString("Subject01Title02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宣纸 的本地化字符串。
        /// </summary>
        public static string Subject01Title03 {
            get {
                return ResourceManager.GetString("Subject01Title03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 澄心堂纸 的本地化字符串。
        /// </summary>
        public static string Subject01Title04 {
            get {
                return ResourceManager.GetString("Subject01Title04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 薛涛笺 的本地化字符串。
        /// </summary>
        public static string Subject01Title05 {
            get {
                return ResourceManager.GetString("Subject01Title05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结语 的本地化字符串。
        /// </summary>
        public static string Subject01Title06 {
            get {
                return ResourceManager.GetString("Subject01Title06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景 的本地化字符串。
        /// </summary>
        public static string Subject02Title01 {
            get {
                return ResourceManager.GetString("Subject02Title01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冲糍图 的本地化字符串。
        /// </summary>
        public static string Subject02Title02 {
            get {
                return ResourceManager.GetString("Subject02Title02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 苗寨六月六 的本地化字符串。
        /// </summary>
        public static string Subject02Title03 {
            get {
                return ResourceManager.GetString("Subject02Title03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 哭嫁 的本地化字符串。
        /// </summary>
        public static string Subject02Title04 {
            get {
                return ResourceManager.GetString("Subject02Title04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阳春三月 的本地化字符串。
        /// </summary>
        public static string Subject02Title05 {
            get {
                return ResourceManager.GetString("Subject02Title05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湘西碾米 的本地化字符串。
        /// </summary>
        public static string Subject02Title06 {
            get {
                return ResourceManager.GetString("Subject02Title06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抗旱图 的本地化字符串。
        /// </summary>
        public static string Subject02Title07 {
            get {
                return ResourceManager.GetString("Subject02Title07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结语 的本地化字符串。
        /// </summary>
        public static string Subject02Title08 {
            get {
                return ResourceManager.GetString("Subject02Title08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D打印笔筒 的本地化字符串。
        /// </summary>
        public static string Subject04Title01 {
            get {
                return ResourceManager.GetString("Subject04Title01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折纸雨伞 的本地化字符串。
        /// </summary>
        public static string Subject04Title02 {
            get {
                return ResourceManager.GetString("Subject04Title02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伸缩纸箱 的本地化字符串。
        /// </summary>
        public static string Subject04Title03 {
            get {
                return ResourceManager.GetString("Subject04Title03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带光纸抽 的本地化字符串。
        /// </summary>
        public static string Subject04Title04 {
            get {
                return ResourceManager.GetString("Subject04Title04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windy纸桌 的本地化字符串。
        /// </summary>
        public static string Subject04Title05 {
            get {
                return ResourceManager.GetString("Subject04Title05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸筒衣架 的本地化字符串。
        /// </summary>
        public static string Subject04Title06 {
            get {
                return ResourceManager.GetString("Subject04Title06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸花瓶外套 的本地化字符串。
        /// </summary>
        public static string Subject04Title07 {
            get {
                return ResourceManager.GetString("Subject04Title07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸做的教堂 的本地化字符串。
        /// </summary>
        public static string Subject04Title08 {
            get {
                return ResourceManager.GetString("Subject04Title08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信纸围巾 的本地化字符串。
        /// </summary>
        public static string Subject04Title09 {
            get {
                return ResourceManager.GetString("Subject04Title09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折叠纸板电话 的本地化字符串。
        /// </summary>
        public static string Subject04Title10 {
            get {
                return ResourceManager.GetString("Subject04Title10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超轻纸鞋 的本地化字符串。
        /// </summary>
        public static string Subject04Title11 {
            get {
                return ResourceManager.GetString("Subject04Title11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸浆头盔 的本地化字符串。
        /// </summary>
        public static string Subject04Title12 {
            get {
                return ResourceManager.GetString("Subject04Title12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸质竹节吸管 的本地化字符串。
        /// </summary>
        public static string Subject04Title13 {
            get {
                return ResourceManager.GetString("Subject04Title13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冷却包装纸 的本地化字符串。
        /// </summary>
        public static string Subject04Title14 {
            get {
                return ResourceManager.GetString("Subject04Title14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸板拼图自行车 的本地化字符串。
        /// </summary>
        public static string Subject04Title15 {
            get {
                return ResourceManager.GetString("Subject04Title15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mini Power应急纸电池 的本地化字符串。
        /// </summary>
        public static string Subject05Title01 {
            get {
                return ResourceManager.GetString("Subject05Title01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸上试鞋 的本地化字符串。
        /// </summary>
        public static string Subject05Title02 {
            get {
                return ResourceManager.GetString("Subject05Title02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸板手机音箱 的本地化字符串。
        /// </summary>
        public static string Subject05Title03 {
            get {
                return ResourceManager.GetString("Subject05Title03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可控纸飞机 的本地化字符串。
        /// </summary>
        public static string Subject05Title04 {
            get {
                return ResourceManager.GetString("Subject05Title04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LED细胞灯纸 的本地化字符串。
        /// </summary>
        public static string Subject05Title05 {
            get {
                return ResourceManager.GetString("Subject05Title05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸质U盘名片 的本地化字符串。
        /// </summary>
        public static string Subject05Title06 {
            get {
                return ResourceManager.GetString("Subject05Title06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体温贴纸 的本地化字符串。
        /// </summary>
        public static string Subject05Title07 {
            get {
                return ResourceManager.GetString("Subject05Title07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸可拍相机 的本地化字符串。
        /// </summary>
        public static string Subject05Title08 {
            get {
                return ResourceManager.GetString("Subject05Title08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子纸显示器 的本地化字符串。
        /// </summary>
        public static string Subject05Title09 {
            get {
                return ResourceManager.GetString("Subject05Title09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蒙德里安便签纸 的本地化字符串。
        /// </summary>
        public static string Subject05Title10 {
            get {
                return ResourceManager.GetString("Subject05Title10", resourceCulture);
            }
        }
    }
}
